Сверстан макет для ревью
atizay/ibs_shop pull request #1
Opened 2021-06-03 15:56 UTC by atizay

2021-06-03 16:29 UTC, Roman-Maksimov requested changes

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  max-width: 1440px;
max-width тут не требуется. Контент должен растягиваться на всю ширину

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +    max-width: 325px;
max-width тут не требуется. Заголовок должен растягиваться на всю ширину

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  max-width: 300px;
Обратите внимание, на мобильной версии ширина поля не больше 200px

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +}
При фокусе на поле иконка тоже должна менять цвет на оранжевый.
PS. Это просто иконка, не обязательно её делать кнопкой

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  border-bottom: 2px solid #E97F03;
На цвет бордера тоже не мешает повесить анимацию

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  display: flex;
Не очень понятно использование flexbox здесь. Абсолютно-спозиционированные элементы (`.search-panel__btn`), не участвуют в компоновке. Т.е. по факту внутри контейнера у вас только один flex-элемент

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  width: 100%;
Поскольку это flex-элемент, лучше использовать flex-свойства (flex-grow, flex-shrink, flex-basis или, как правило всё это записывают одним общим свойством flex)

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  margin-bottom: 52px;
Когда вы будете натягивать верстку на реальные данные, вряд ли вы будете знать точный размер изображения. Тут требуется что-то более относительное.

2021-06-03 16:29 UTC, Roman-Maksimov commented on product-page.html
> +  <footer></footer>
Пустой тэг - лишняя нода в DOM-дереве. Если элемент не несет функциональной или визуальной нагрузки, нет смысла его создавать.

2021-06-03 16:29 UTC, Roman-Maksimov commented on product-page.html
> +                  <input type="button" value="+" class="quantity__plus">
Напоминаю про самозакрывающиеся тэги

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +}
Полагаю, еще тени не хватает

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  transition: all .05s ease-in;
У вас уже есть `transition` на `.btn`, дублировать нет смысла

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +@media (max-width: 575px) {
Для каталога подходит, но для детальной страницы, очевидно, маловато. Лучше сделать два media-запроса для разных страниц

2021-06-03 16:29 UTC, Roman-Maksimov commented on style.css
> +  }
Блок с картинкой на мобильной версии должен быть растянут по всей ширине окна без отступов слева и справа

2021-06-03 19:12 UTC, Roman-Maksimov requested changes

2021-06-03 19:12 UTC, Roman-Maksimov commented on index.html
> +            <label for="">
пустые атрибуты `action`  и `for` не нужны.

2021-06-03 22:48 UTC, Roman-Maksimov requested changes

2021-06-03 22:48 UTC, Roman-Maksimov commented on style.css
> +  padding: 71px 0 29px 0;
это можно сократить до `padding: 71px 0 29px;`

2021-06-03 22:48 UTC, Roman-Maksimov commented on style.css
> +  width: calc(100%/2);
Почему бы не просто `width: 50%`? `calc` - для браузер, это всегда дополнительная калькуляция на этапе reflow. Использование `calc` должно быть осторожно и обосновано.

2021-06-03 22:48 UTC, Roman-Maksimov commented on style.css
> +    justify-content: space-between;
Думаю, `space-around` тут больше подойдет

2021-06-03 22:49 UTC, Roman-Maksimov requested changes

2021-06-03 22:49 UTC, Roman-Maksimov commented on index.html
> +              <input type="search" class="search-panel__input" placeholder="Search products">
самозакрывающийся тэг

2021-06-04 05:38 UTC, atizay commented on style.css
> +  width: calc(100%/2);
Хочу объяснить причину - по макету думал, что фото товара занимает 1/2 или 1/3 ширины карточки, поэтому использовал calc(). Но уже когда более-менее подошло значение 100%/2 - не заменил на просто 50%.
Согласен, что в данном случае лучше написать просто 50%

2021-06-04 14:50 UTC, Roman-Maksimov approved these changes

2021-06-04 15:48 UTC, merged